name: Docker

on:
  push:
    # Publish `robuust` branch to Container Registry
    branches: 'pdo_sqlsrv'

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest-arm64
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx        
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push image to GitHub Container Registry
        run: docker buildx build --pull --platform=linux/arm64,linux/amd64 --tag ghcr.io/robuust/heroku-php-build-heroku-24 --file $(pwd)/support/build/_docker/heroku-24.Dockerfile --push .
  php83:
    # Ensure push job passes before pushing image.
    needs: push

    runs-on: ubuntu-latest-arm64
    if: github.event_name == 'push'

    steps:
      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v3

      - name: Build & deploy php 8.3
        run: docker run --rm -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" ghcr.io/robuust/heroku-php-build-heroku-24 deploy.sh php-8.3.14 --overwrite

      - name: Build & deploy ext-pdo_sqlsrv for php 8.3
        run: docker run --platform=linux/arm64 --rm -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" ghcr.io/robuust/heroku-php-build-heroku-24 deploy.sh extensions/no-debug-non-zts-20230831/pdo_sqlsrv-5.12.0 --overwrite

      - name: Build & deploy ext-pdo_sqlsrv for php 8.3 (x86)
        run: docker run --platform=linux/amd64 --rm -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" ghcr.io/robuust/heroku-php-build-heroku-24 deploy.sh extensions/no-debug-non-zts-20230831/pdo_sqlsrv-5.12.0 --name=extensions/no-debug-non-zts-20230831/pdo_sqlsrv-5.12.0-x86 --overwrite
